In [64]:

#He cheo troi
A = [[ -15.4 , 1 , 6.3] , [ -4.2 , 10.8 , 3.3] , [ -2.4 , 5.3 , 15.9]]
b = [30 , 25 , -10]
m = lambda i , j : -A [ i ][ j ] / A [ i ][ i ] if i != j else 0


In [65]:
import numpy as np
B = np . array ([ [ m (i , j ) for j in range (3) ] for i in range (3) ])
B

array([[ 0.        ,  0.06493506,  0.40909091],
       [ 0.38888889,  0.        , -0.30555556],
       [ 0.1509434 , -0.33333333,  0.        ]])

In [66]:
g = [ b [ i ] / A [ i ][ i ] for i in range (3) ]
g

[-1.948051948051948, 2.314814814814815, -0.6289308176100629]

In [67]:
q = np . linalg . norm (B , np . inf )
q

0.6944444444444444

In [68]:
x = [0 , 0, 0]
for _ in range (3) :
     x = B .dot ( x ) + g
     print ( x )

[-1.94805195  2.31481481 -0.62893082]
[-2.05502918  1.74941236 -1.69458133]
[-2.52769156  2.03342554 -1.52226136]


In [69]:
x0 = [0 , 0 , 0] # lưu x
for _ in range (3) :
     x = B . dot ( x0 ) + g # x
     ss = q / (1 - q) * np . linalg . norm ( x - x0 , np . inf )
     x0 = x # tiến thêm 1 bước
     print (x , ss )

[-1.94805195  2.31481481 -0.62893082] 5.26094276094276
[-2.05502918  1.74941236 -1.69458133] 2.4219329894001134
[-2.52769156  2.03342554 -1.52226136] 1.0742326887266849


In [70]:
x0 = [0 , 0 , 0]
k = 0
while True :
     x = B . dot ( x0 ) + g
     ss = q / (1 - q) * np . linalg . norm ( x - x0 , np . inf )
     x0 = x
     k += 1
     print (k , x , ss )
     if ss < 10** -3:
            break


1 [-1.94805195  2.31481481 -0.62893082] 5.26094276094276
2 [-2.05502918  1.74941236 -1.69458133] 2.4219329894001134
3 [-2.52769156  2.03342554 -1.52226136] 1.0742326887266849
4 [-2.43875461  1.79695907 -1.68827768] 0.5374238079127538
5 [-2.52202535  1.88227287 -1.59603108] 0.20965137241702506
6 [-2.47874824  1.82170334 -1.63703818] 0.13765801368867453
7 [-2.49945696  1.85106328 -1.61031594] 0.06672711991270326
8 [-2.48661865  1.83484476 -1.62322843] 0.036860268116862216
9 [-2.49295418  1.84378292 -1.6158844 ] 0.020313999410520586
10 [-2.4893694   1.83907509 -1.61982009] 0.010699608187099544
11 [-2.49128516  1.84167174 -1.61770972] 0.005901483318229957
12 [-2.49025321  1.84028189 -1.61886444] 0.0031587593684227625
13 [-2.49081585  1.84103603 -1.61824539] 0.0017139662390384313
14 [-2.49051363  1.84062808 -1.6185817 ] 0.0009271760305810823


In [71]:
x0 = [0 , 0 , 0]
x1 = B . dot ( x0 ) + g
from sympy import log
log ( 10** -8 * (1 - q ) / np . linalg . norm ( x1 - x0 , np . inf ) , q )

56.0702597648784

In [72]:
x = [0 , 0 , 0]
for _ in range (4) : # bước lặp
     for i in range (3) : # thành phần
         x [ i ] = B [ i ]. dot ( x ) + g [i ] # cập nhật lần lượt từng thành phần
         print ( x )

[-1.948051948051948, 0, 0]
[-1.948051948051948, 1.5572390572390573, 0]
[-1.948051948051948, 1.5572390572390573, -1.4420560804208602]
[-2.4368645616501534, 1.5572390572390573, -1.4420560804208602]
[-2.4368645616501534, 1.8077735098572403, -1.4420560804208602]
[-2.4368645616501534, 1.8077735098572403, -1.5993506006417446]
[-2.4849438489731006, 1.8077735098572403, -1.5993506006417446]
[-2.4849438489731006, 1.8371382237435865, -1.5993506006417446]
[-2.4849438489731006, 1.8371382237435865, -1.6163960895205314]
[-2.490010203911413, 1.8371382237435865, -1.6163960895205314]
[-2.490010203911413, 1.8403763184249833, -1.6163960895205314]
[-2.490010203911413, 1.8403763184249833, -1.6182401872352077]
