In [1]:
##lap diem bat dong
import numpy as np
A = [[5 , 0 , 2] , [3 , -2 , -4]]
np . linalg . norm (A , 1)
np . linalg . norm (A , np . inf )
np . linalg . norm (A , 2)

5.999999999999999

In [2]:
import numpy as np
B = np . array ( [[ -0.21 , -0.28 , 0.05] ,
[ 0.19 , 0.01 , -0.26] ,
[ 0.39 , -0.12 , -0.06]] )
g = [ -0.9 , 3.8 , -2.9]
q = np . linalg . norm (B , np . inf )
q

0.5700000000000001

In [3]:
x = [0 , 2 , -1]
for _ in range (3) :
     x = B .dot ( x ) + g
     print ( x )

[-1.51  4.08 -3.08]
[-1.8793  4.3547 -3.7937]
[-1.914348  4.472842 -3.927869]


In [4]:
x0 = [0 , 2 , -1] # lưu x
for _ in range (3) :
     x = B . dot ( x0 ) + g # x
     ss = q / (1 - q) * np . linalg . norm ( x - x0 , np . inf )
     x0 = x # tiến thêm 1 bước
     print (x , ss )

[-1.51  4.08 -3.08] 2.7572093023255824
[-1.8793  4.3547 -3.7937] 0.9460674418604651
[-1.914348  4.472842 -3.927869] 0.17785193023255816


In [5]:
x0 = [0 , 2 , -1]
k = 0
while True :
     x = B . dot ( x0 ) + g
     ss = q / (1 - q) * np . linalg . norm ( x - x0 , np . inf )
     x0 = x
     k += 1
     print (k , x , ss )
     if ss < 10** -3:
            break


1 [-1.51  4.08 -3.08] 2.7572093023255824
2 [-1.8793  4.3547 -3.7937] 0.9460674418604651
3 [-1.914348  4.472842 -3.927869] 0.17785193023255816
4 [-1.94677613  4.50224824 -3.94766462] 0.042986125813954085
5 [-1.94918975  4.50152782 -3.9626526 ] 0.0198677904906978
6 [-1.94923057  4.5049589  -3.96260818] 0.004548180077023621
7 [-1.95018048  4.50497391 -3.9630385 ] 0.0012591831064359337
8 [-1.95000672  4.50490546 -3.96338495] 0.0004592434069525706


In [6]:
x0 = [0 , 2 , -1]
x1 = B . dot ( x0 ) + g
from sympy import log
log ( 10** -8 * (1 - q ) / np . linalg . norm ( x1 - x0 , np . inf ) , q )

35.5743563544289

In [7]:
#Seidel
x = [0 , 2 , -1]
for _ in range (4) : # bước lặp
     for i in range (3) : # thành phần
         x [ i ] = B [ i ]. dot ( x ) + g [i ] # cập nhật lần lượt từng thành phần
         print ( x )

[-1.5100000000000002, 2, -1]
[-1.5100000000000002, 3.7931, -1]
[-1.5100000000000002, 3.7931, -3.8840719999999997]
[-1.8391716000000002, 3.7931, -3.8840719999999997]
[-1.8391716000000002, 4.498347116, -3.8840719999999997]
[-1.8391716000000002, 4.498347116, -3.92403425792]
[-1.969512869376, 4.498347116, -3.92403425792]
[-1.969512869376, 4.49102493303776, -3.92403425792]
[-1.969512869376, 4.49102493303776, -3.971590955545971]
[-1.9424688264589114, 4.49102493303776, -3.971590955545971]
[-1.9424688264589114, 4.508454820745137, -3.971590955545971]
[-1.9424688264589114, 4.508454820745137, -3.9602819634756337]
